[package]
name = "mdbook-frontmatter-strip"
version = "1.1.1"
edition = "2024"
description = "mdBook preprocessor that strips YAML frontmatter from chapters"
license = "Apache-2.0"
repository = "https://github.com/saylesss88/mdbook-frontmatter-strip"
readme = "README.md"
keywords = ["mdbook", "rss", "feed", "preprocessor", "blog"]
categories = ["command-line-utilities", "web-programming"]

[dependencies]
anyhow = {version = "1.0.102", default-features = false}
serde_json = "1.0.150"

[[bin]]
name = "mdbook-frontmatter-strip"
path = "src/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
debug = false
